FileVersion = 1

[Project]
Name = "lodepng-beef"
DefaultNamespace = "lodepng"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\lodepng_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\lodepng.lib"]