FileVersion = 1

[Project]
Name = "lodepng-beef"
DefaultNamespace = "lodepng"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\debug\\lodepng.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\release\\lodepng.lib"]